// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SotaApp.Data;

#nullable disable

namespace SotaApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250503181559_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SotaApp.Data.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusteriSoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("SotaApp.Data.Satici", b =>
                {
                    b.Property<int>("SaticiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaticiAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaticiSoyadi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("SaticiId");

                    b.ToTable("Saticilar");
                });

            modelBuilder.Entity("SotaApp.Data.Satis", b =>
                {
                    b.Property<int>("SatisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusteriId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SatisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SatisId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("UrunId");

                    b.ToTable("Satislar");
                });

            modelBuilder.Entity("SotaApp.Data.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SaticiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("UrunId");

                    b.HasIndex("SaticiId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("SotaApp.Data.Satis", b =>
                {
                    b.HasOne("SotaApp.Data.Musteri", "Musteri")
                        .WithMany("Satis")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SotaApp.Data.Urun", "Urun")
                        .WithMany("Satis")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("SotaApp.Data.Urun", b =>
                {
                    b.HasOne("SotaApp.Data.Satici", "Satici")
                        .WithMany("Urunler")
                        .HasForeignKey("SaticiId");

                    b.Navigation("Satici");
                });

            modelBuilder.Entity("SotaApp.Data.Musteri", b =>
                {
                    b.Navigation("Satis");
                });

            modelBuilder.Entity("SotaApp.Data.Satici", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("SotaApp.Data.Urun", b =>
                {
                    b.Navigation("Satis");
                });
#pragma warning restore 612, 618
        }
    }
}
